language: java
jdk:
- oraclejdk8
sudo: false
deploy:
  edge: true
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: gina.debeukelaer@ordina.be
  password:
    secure: f+400dEQy3BXVVW8P1lA9KoMxUmgcpM00Qii0FFuvNr55lijD28y7SpzbcEa3G+P89MQdbSN6m1fhVny5lXg2vzuoI97sZKYFf5Ckfqq4z8SgkQeriVj/1W2NRY+YRRs5Kg+3nm8PX00mFLjkQ+mcHcePAyiLnSDR+Dro5snbKMpT5MoWcc6skHyaBBj1iZVhMIX0N8OK3T4CYIYT6t3gKwwQQOMbTL65qi89EI0BHELwrQLMIbzRSSt7n7s36k0v/j/Y7kxyD0c0TjZwRJEU8fe6qB5izaGA+CobAG1fqcdXWREhAzIFw0so+hjW+4cJpXzLjMp/PwgK5HUqlif2/wipp1Nt2ED9BIAZysSFum2SPy2c8bPk2q9oM9inxwM9OIBV+UGbIxIdPKCeNPb+tODPDLZSCcm8vYJYo+P6+/4hqB+A4L2PnTE5IQaSTxfwhxWyQSEjS+kU4pz3YJvJKtwL5kKFlHzXRfh0LX1pFmMr275qAeM+SGLLt4GC4IuW02WUVgeSVaKcvLt7r1wCFhSczJeffTN0OvLLldaNcqCn2Ia99LHsZsusSa+tfARc8AJ/VrNWSn+8A4LomWu700/ck4swrKsh1qbpqFo4zwVA9Nnms9jajWKOvui7hhSYejvPoUOUVhIrTjltC0GqnbJHWECbQbQa50CNqyMafg=
  organization: OrdinaBelgiumNV
  space: development
  on:
    repo: Ordineo/gateway
    branch: master
notifications:
  slack:
    secure: JkT3RYroRoUqTUbAhLaaAdNxneWh2cq22yNqBizqrErHtXH6DA7W08kAy5USbs9yf50iwdcEIo1poJ7pZxavyWIB4WMPUd2dZF/40GWyhz4v0OHiQ42EhM7Fa/uVJxVitEwsiKoCqAm4/B53+/VRHtCIWjYnUOcvGOWCBrGjbufj4wO4/GuDPBuYT4UjD8DGlos2PLx2pqfumyx60wRi76ff/79KaqATXVcOEhAwNrJPzKNO5o1tg7Eu0SUOuI0C+rEPJbPetv0nN8cKliAzGYJbMGUNIz7zg8CnPDzVgmmQAAGfeNC/q817RfqgcJZO6+/QH+0DbMhQ3J/u6QzKXlqd+p9R6Sn4YZhVQlwzi3zECU/zJ/Mm49eW1g3qamXE+V6ukUcV2uoK4bMJgDgbGwewbEDf0UJPZhM69XqlallXNRUfzxd4QpfKrbS5zMh2v2k1Kc3c1d2ASCy2Il3LM56UHIE/XYWozZ+eJ3TPS0Xal51zexuQKzB+dBBdApqRRl4n0gu2DRp2jKNHMiUH8hhXppi+LX8awzn3bwiWX8YKILHXsfzCq3I4tknr1TsKxVIUpUaAGQXEe8xjxqtYZWozq3fjo7cYGzQFfGhqWI2D99E6+loi7n+CzkkSAwAJbVLYfMMg6OMRQCVgP1fjYpa67EhOixvzP8qWX6FKflk=
