server:
  port: ${PORT:9900}
debug: true
#spring:
#   redis:
#       host: pub-redis-10962.us-east-1-2.5.ec2.garantiadata.com
#       database: 0
#       port: 10962
#       password: r1b098ipgrR9jJ7t
#  aop:
#    proxy-target-class: true
jwt:
  header: Authorization
  secret: 360t00l
  expiration: 604800
  route:
    authentication:
      path: auth
      refresh: refresh

---
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone:  https://eureka-ordineo.cfapps.io/eureka/ #http://localhost:8761/eureka/
  instance:
    secure-port-enabled: true
    secure-port: ${server.port}
    non-secure-port-enabled: false
ribbon:
  IsSecure: true
---
#zuul:
#  ignored-services: "*"
#  routes:
#    milestones:
#      path: /milestone-ordineo/**
#      serviceId: milestone-ordineo
#      stripPrefix: false
#      sensitive-headers:
#    employees:
#      path: /employee-ordineo/**
#      serviceId: employee-ordineo
#      stripPrefix: false
#      sensitive-headers:
logging:
  level:
    org.springframework.security: DEBUG
spring:
  profiles: cloud
server:
  port: ${PORT}
eureka:
  instance:
    hostname: ${vcap.application.uris[0]}
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    non-secure-port: 80
    non-secure-port-enabled: false
    secure-port-enabled: true
  client:
    serviceUrl:
      defaultZone: ${vcap.services.registry.credentials.url}
    healthcheck:
      enabled: true