server:
  port: ${PORT:9900}
debug: true
spring:
  aop:
    proxy-target-class: true
jwt:
  header: Authorization
  secret: 360t00l
  expiration: 604800
  route:
    authentication:
      path: auth
      refresh: refresh

---
eureka:
  client:
    serviceUrl:
      defaultZone: https://eureka-ordineo.cfapps.io/eureka/ #http://localhost:8761/eureka/
ribbon:
  IsSecure: true
---
zuul:
 routes:
    resource:
      path: /resource/**
      url: http://employee-ordineo.cfapps.io/
      sensitive-headers:
logging:
  level:
    org.springframework.security: DEBUG
spring:
  profiles: cloud
server:
  port: ${PORT}
eureka:
  instance:
    hostname: ${vcap.application.uris[0]}
    nonSecurePort: 80
    nonSecurePortEnabled: false
    securePortEnabled: true
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    serviceUrl:
      defaultZone: ${vcap.services.registry.credentials.url}
    healthcheck:
      enabled: true